import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import AuthContext from "./components/AuthContext";
import Sidebar from "./sidebar";
import Footer from "./footer";
const inter = Inter({ subsets: ["latin"] });
import Breadcrumb from "./components/Breadcrumb";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Navbar></Navbar>
          <Breadcrumb
            homeElement={"Home"}
            separator={<span>/</span>}
            activeClasses="text-slate-100"
            containerClasses="flex"
            listClasses="hover:underline mx-2 text-slate-400"
            capitalizeLinks
          />
          <div className="relative flex h-screen overflow-hidden">
            {/* <Sidebar></Sidebar> */}
            <div className="flex-1 overflow-y-auto h-screen">
              <div className="m-2"></div>
              <div className="min-h-[calc(100vh-20rem)]">{children}</div>
              <Footer></Footer>
            </div>
          </div>
        </AuthContext>
      </body>
    </html>
  );
}
