import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import AuthContext from "./components/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Navbar></Navbar>
          <div className="my-4">{children}</div>
        </AuthContext>
      </body>
    </html>
  );
}
