import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/layout/Navbar";
import NavbarD from "../components/layout/NavbarDaisy";
import AuthContext from "../components/layout/AuthContext";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar2 from "@/components/layout/Navbar2";

const inter = Inter({ subsets: ["latin"] });
import Breadcrumb from "./components/Breadcrumb";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthContext>
            <Navbar></Navbar>
            <NavbarD></NavbarD>
            {/* <Navbar2></Navbar2> */}
            {children}
          </AuthContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
